//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Record
    {
        public int Id { get; set; }
        public int Id_Client { get; set; }
        public int Id_Service { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public string Additional_Commentary { get; set; }
        public string Additional_Scans { get; set; }
    }
}
