//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronym { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public System.DateTime Data_First_Visit { get; set; }
        public string Photo { get; set; }
        public string Tag { get; set; }
        public string Tag_Color { get; set; }
    }
}
