//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Work_Start_Date { get; set; }
    }
}
